import { unstable_setRequestLocale } from "next-intl/server";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/global-components/navbar";
import Footer from "./components/global-components/footer";

const locales = ["en", "de", "pl"];

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Goliat",
  description: "",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function LocaleLayout({ children, params: { locale } }) {
  if (!locales.includes(locale)) notFound();
  unstable_setRequestLocale(locale);
  // const t = useTranslations("Navbar");
  // const tf = useTranslations("Footer");

  return (
    <html lang={locale}>
      {/* <Navbar /> */}
      <body className={inter.className}>
        {/* <Navbar
          start={t("start")}
          about={t("about")}
          projects={t("projects")}
          getInspired={t("get inspired")}
          news={t("news")}
          contact={t("contact")}
          locale={locale}
        /> */}
        {children}
        {/* <Footer
          about={tf("about")}
          office={tf("office")}
          contact={tf("contact")}
          locale={locale}
        /> */}
        <Footer />
      </body>
    </html>
  );
}

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
